name: Build and Publish to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      id: build
      run: |
        docker build -t ghcr.io/quantumlyconfused/qcadmin-discord-bot:latest .

    # Only push the image if the build step is successful
    - name: Push Docker image
      if: ${{ success() }}
      run: |
        docker push ghcr.io/quantumlyconfused/qcadmin-discord-bot:latest